# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel

sudo: required

env:
  global:
    secure: lKBm/EWtq7SCoeHpQhjkFTxefLld3laZNKVtXmDSwUvZ5ju6fH2xrosBHTVrYWzfiEbSOA6phAqKPV3NvghSgaXBtTPf5htudLyX+z/kAbVNIDt6fFuOpqhj7Vjz4eqS0bfKnjeNr64bMx0kUUHnPZjYFSlXFOjaULbW0QZyhWCKJNYQp4NSycdoVLIS6J+TWbTgmsKBzM23QKmu7nBij/fP+pn8r9FHSVxNy8QV2HLgqdbnDFq/bdWgES0Ay0BMv/Fe7RgvS+zNmtyGcQ78Wmcpce+26HcSkhdVhtAnHbZaU/1IXiggPNfQcIOjdmtkcoipkYrImSBPkdg/tEyXZfxGx6QpkhNAmQOMAXgdaxt9jSgXdV+ILNvlOXINTBx+n890qXhQvY/uj2HZPZ0O4Y0DlZ1eblAq9t3hatG1L63X30LLBPOVzmcQAH2NFmjQjLNd8V7mIBGyqnWgIJqxRa6MxdzjZOUgn/reVy5ycrORSiVNecratwJELXkIuQUiwu6lYRkjwQSUtJvtYt70WJsxXMBo3LSNEd8HSVHeaobnO9nLrNxYy7Mxd65/4jvnXQuCGoIImSrNi/sefDxCEUUCffO6KadE7qlxoiyHHYGK5f7xhUcYVSAPALcOQjG2k1Afzlk2UTWWXXRBWVv2toMUDbBAtZtVPRlpwLqCueg=

before_install:
  - cd pkg

warnings_are_errors: true

cache: packages

r_packages:
  - testthat
  - rmarkdown
  - R2HTML
  - doParallel
  - parallel
  - foreach
  - magrittr
  - SuperLearner
  - tmle

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
